### ISSUE TITLE
Content Tree React - Action bar - Reorder (drag & drop)

### ISSUE THREAD

**Issue by jeffdoolittle** [trimble-oss/website-modus-react-bootstrap.trimble.com#123]
The Drag & Drop icon (and functionality) is hidden by default. The user needs to click the icon in the action bar above the content Tree.
 * Click the Drag & Drop icon.
 * The tree shows the Drag & Drop icon in front of each item in the tree.
 * The user can still expand the tree to be able to drag and drop into a different folder.
 * Change size of search box (leftover from #124 ) 

Content tree items can be dragged and dropped as a way of reordering or restructuring the hierarchy. Multiple content tree items can be dragged and reordered simultaneously. When selecting items in different hierarchies, dropping them in a new location flattens their hierarchical relationship with one another as sibling children of the content tree item they were dropped into.

The content tree DOES NOT accept dropped items from outside the component (e.g., dropping a new file into a content tree in order to upload a file to a specific folder is not allowed).

If a drag operation is not allowed, the line indicating the drop location will be red, and when the user tries to drop it, the item will return to its original location.

**Comment by msankaran0712** [comment]
@Balaji-trimble Please QA

**Comment by Balaji-trimble** [comment]
QA Status

**Verified the following scenarios** 
- Verified whether the drag and drop icon is present.
- Verified whether drag and drop icon is present before each option in tree after clicking it.
- Successfully checked the rearranging the tree using drag and drop.
- Verified whether the tree item is highlighted in red if it cannot be rearranged.
- Verified whether the tree item is highlighted in blue if it can be rearranged.
- Verified whether the tree item is highlighted in red if it cannot be rearranged and it is moved back to original position.
- Verified whether the search bar size is changed in **_Tree with Filter_**.

Notify : @msankaran0712 @enowak1031
