### ISSUE TITLE
Global Search - React

### ISSUE THREAD

**Issue by jeffdoolittle** [trimble-oss/website-modus-react-bootstrap.trimble.com#125]
As an engineer working in React, I want to have the global search feature available in the table component, so I can offer extended table functionality to my users.

- [x]  * Search field should be located above the table header and/or collocated with any horizontal toolbar.
- [x]  * Search field should use the Modus “Input with icon on left,” and utilize the magnifying glass icon.
- [x]  * Once a string is entered, the “content close” icon should appear at the right internal edge of the field, allowing the user to cancel the search / delete the string.

 * App Specific: It is at the product team's discretion to update the table real time as a string is entered or after a return.
 * Optional: Magnifying glass icon can be used on its own, upon a user clicking the icon it should expand into the input field state prescribed above.

**Comment by Balaji-trimble** [comment]
Verified this ticket. Hence moving this ticket to PO review.

Notify : @msankaran0712 @enowak1031
