### ISSUE TITLE
Content Tree React - Keyboard integrations

### ISSUE THREAD

**Issue by jeffdoolittle** [trimble-oss/website-modus-react-bootstrap.trimble.com#127]
* Refer to the screenshot for how to navigate through Tree items
 * Tree Item selection:
- [x] **  Shift + Click should select a range (see first example). Ctrl + click selects multiple individual items (see 2nd example). 
- [x] #160

**Comment by msankaran0712** [comment]
Clarification needed:
- [ ] Which keys are used for selection and expand/collapse
- [ ] Are Up and Down Arrow keys used to navigate up and down the Content Tree items? 
- [ ]

**Comment by msankaran0712** [comment]
@Balaji-trimble  Ready for QA https://deploy-preview-159--modus-react-bootstrap.netlify.app/components/content-tree/#Accessibility

**Comment by Balaji-trimble** [comment]
Verified the Keyboard Navigation - Please find the below observation

Selecting an expandable/collapse option and tapping the enter key does not toggle the them.

**Comment by Balaji-trimble** [comment]
> @msankaran0712 @enowak1031 Verified the Keyboard Navigation - Please find the below observation
> 
> Selecting an expandable/collapse option and tapping the enter key does not toggle them.

@msankaran0712 This is working as expected

**Comment by Balaji-trimble** [comment]
@msankaran0712 Please find the below issue observed
**Tree with actions** 

-   Navigate to leaf node of any hierarchy
-   click ctrl + leaf node
-   Tree disappears
-   On clicking show code /hide code tree appears again

 
**Error Message**
  TypeError: Cannot read properties of null (reading 'focus')

**Refer** - Attached screenshot

![image](https://user-images.githubusercontent.com/60882376/166233542-d888d16d-2873-4679-8642-b399d9db36cd.png)

**Comment by msankaran0712** [comment]
@Balaji-trimble am closing this issue for now, if you were able to reproduce the above issues we can raise a new issue
