### ISSUE TITLE
Column Sorting - React

### ISSUE THREAD

**Issue by jeffdoolittle** [trimble-oss/website-modus-react-bootstrap.trimble.com#134]
As an engineer working in React, I want to have the column sorting feature available in the table component, so I can offer extended table functionality to my users.

 
 * Ascending order (A-Z, 1-9), indicated by arrow facing up ↑
 * Descending order (Z-A, 9-1), indicated by arrow facing down ↓
 * Sorted column: Use arrow symbol indicator in column header
 * Column with no sort: No symbol
 * Sorting Behavior: 
 * When no sort is present: on-hover, display arrow symbol with tooltip “Sort ascending”
 * Click once: Sort ascending, arrow symbol persists
 * On-hover: Display sort descending symbol with tooltip, “Sort descending”
 * Click again: Sort descending, arrow symbol persists
 * On-hover: Hide arrow symbol with tooltip, “Remove sort”
 * Click again: Remove sort, remove arrow symbol entirely

**Comment by msankaran0712** [comment]
The feature was already implemented https://jira.trimble.tools/browse/DDS-327
