### ISSUE TITLE
Modus React Bootstrap Release v1.1.0

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/website-modus-react-bootstrap.trimble.com#145]
The release should have the following elements,
- [x] New component - Content Tree
- [x] Update Table components and improve API details
- [x] Update modus-bootstrap package version
- [x] Proofread and validate each example code, API details, and instructions
- [x] Test examples in the List component and other components like Content Tree which uses list classes after upgrading the modus-bootstrap package, make sure there are no inconsistencies
- [x] Verify Accessibility for Table and Content tree components
- [x] Test Large Tree view, to ensure it can be implemented
- [x] Fix the ESLint issues, console errors, build warnings, issues reported by Christian in modus-react-bootstrap and the site if possible
- [x] Content Tree - Add/Edit - Text input field loses focus if not the workaround 
            onFocus={e => {}} // to retain the focus

- [x] Upgrade react-table to v7.8

**Comment by coliff** [comment]
@msankaran0712 
can this be closed now?
