### ISSUE TITLE
React - Indeterminate checkbox not working for any component in the site examples

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/website-modus-react-bootstrap.trimble.com#160]
The bug is replicable only on a gatsby site on production,
sample gatsby site to view the bug - https://62834daa8b1f623d42994bfe--remarkable-sunburst-705f95.netlify.app/

fixed on site - https://deploy-preview-170--modus-react-bootstrap.netlify.app/components/content-tree/#MultiSelectionTree

**Comment by msankaran0712** [comment]
@Balaji-trimble Please QA

**Comment by Balaji-trimble** [comment]
@msankaran0712 Verified in QA

**Comment by msankaran0712** [comment]
@enowak1031 reviewed it
