### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by coliff** [trimble-oss/website-modus-react-bootstrap.trimble.com#213]
I think this project should include a license file. The `package.json` states that this is 0BSD but I think it should probably be MIT to match all our other open source projects. Also React Bootstrap itself is MIT:
https://github.com/react-bootstrap/react-bootstrap/blob/bs4-dev/LICENSE

cc @jeffdoolittle

**Comment by jeffdoolittle** [comment]
Agreed. MIT is my recommended default for OSS projects.
