### ISSUE TITLE
Create a Changelog

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/website-modus-react-bootstrap.trimble.com#83]
The file should live at the root of the project and be called "CHANGELOG.md"

Use [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) as a guide.

Every release should highlight new features, bug fixes, and breaking changes.

**Comment by coliff** [comment]
shall we close this issue? We already have a CHANGELOG for the library.
https://github.com/trimble-oss/modus-react-bootstrap/blob/main/CHANGELOG.md

don't think we need one for the site.
